"""create_users_and_auth_tables

Revision ID: 04b5d582401d
Revises: 
Create Date: 2026-09-02 15:40:33.261490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b5d582401d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('reporter_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key(None, 'issues', 'users', ['reporter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'assignee_id')
    op.drop_column('issues', 'reporter_id')
    # ### end Alembic commands ###
