"""add organizations invites tenant structure and update user roles

Revision ID: 0579064a3aa1
Revises: 04b5d582401d
Create Date: 2026-09-10 16:37:30.679104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0579064a3aa1'
down_revision: Union[str, Sequence[str], None] = '04b5d582401d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # Migrate existing role strings
    op.execute("UPDATE users SET role = 'internal_admin' WHERE role = 'admin'")
    op.execute("UPDATE users SET role = 'internal_member' WHERE role = 'member'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'organization_id')
    # ### end Alembic commands ###
